### PR TITLE
fix: Multiple bugs - settings text fields, dropdowns, missing override duty cycle, and MQTT icon display

### LINKED ISSUE #3324: [Bug]: The 'Override Duty Cycle' checkbox has disappeared in the LoRa module settings.
### Contact Details

smtp.iforand@gmail.com

### Checklist

- [x] I am able to reproduce the bug with the latest version.

- [x] I made sure that there are no existing **OPEN or CLOSED issues** which I could contribute my information to.

- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

- [x] This issue contains only one bug.

- [x] I have read and understood the **Contribution Guidelines**.

- [x] I agree to follow this project's Code of Conduct

### Affected app version

2.7.1

### Affected Android version

Any

### Affected phone model

Any

### Affected node model

Any

### Affected node firmware version

Any

### Steps to reproduce the bug

In the new source code, neither the file LoRaConfigItemList.kt nor anywhere else except the translation files mentions "override_duty_cycle". It seems to me this option was forgotten to be carried over.

### Actual behavior

The 'Override Duty Cycle' checkbox is missing in the LoRa settings.

### Expected behavior

There is an 'Override Duty Cycle' checkbox present in the LoRa settings.

### Screenshots/Screen recordings

_No response_

### Relevant log output

```shell

```

### Additional information

_No response_

### LINKED ISSUE #3434: [Bug]: Inconsistent display of "MQTT" cloud to indicate a message has travelled through MQTT
### Contact Details

domusonline@gmail.com, domusonline

### Checklist

- [x] I am able to reproduce the bug with the latest version.

- [x] I made sure that there are no existing **OPEN or CLOSED issues** which I could contribute my information to.

- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

- [x] This issue contains only one bug.

- [x] I have read and understood the **Contribution Guidelines**.

- [x] I agree to follow this project's Code of Conduct

### Affected app version

2.7.2

### Affected Android version

Android 15

### Affected phone model

Samsung Galaxy A34

### Affected node model

Heltec V3

### Affected node firmware version

2.7.11

### Steps to reproduce the bug

Hard to reproduce as it involves radios and MQTT server. But the effect can be easily checked by confronting a message display (without "mqtt cloud") whith the message details in the Debug Panel.

### Actual behavior

In some cases the MQTT clound is not shown when the message has the via_mqtt flag.

Further more, I had situations where the cloud is visible at one point, but if for example we remove the matching node from the Node DB and check the message again, the cloud is not shown.
The showing or not of the cloud is a direct consequence of the message and can't be influenced by any characteristics of the node, or weather or not it's in the Node DB.

### Expected behavior

If a message contains via_mqtt : true, the "mqtt cloud" must be displayed.
If the message does not contain the flag (and the flag will never exist wihth value "false" then we enter into a more complex scenario: If the node showing the message effectively got it from the MQTT server, then the flag will not be set (it's set if the node decides to broadcast it through RF).
In this more complex case if the firmware is recent and already contains the transport method in the header, that should be checked and if it's "MQTTT" then the cloud should be shown.

Not sure if whoever looks into this wants to review all the cases of if different bug reports will be needed.

### Screenshots/Screen recordings

Check the message from shortname "Luis":
Image

And as can be seen here, the message has the via_mqtt flag on.
Image

### Relevant log output

```shell

```

### Additional information

_No response_

### LINKED ISSUE #3548: [Bug]: External Notification Nag timeout cannot be set
### Contact Details

_No response_

### Checklist

- [x] I am able to reproduce the bug with the latest version.

- [x] I made sure that there are no existing **OPEN or CLOSED issues** which I could contribute my information to.

- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

- [x] This issue contains only one bug.

- [x] I have read and understood the **Contribution Guidelines**.

- [x] I agree to follow this project's Code of Conduct

### Affected app version

2.7.4

### Affected Android version

Android 13

### Affected phone model

Xiaomi Redmi Note 10 Pro

### Affected node model

Wio Tracker L1

### Affected node firmware version

2.7.11

### Steps to reproduce the bug

Go to Node Configuration / External Notification Config

Try to change Nat Timeout. It turns blank. Selected value is not applied.

### Actual behavior

Selected value is not applied.

### Expected behavior

Selected value should be applied.

### Screenshots/Screen recordings

_No response_

### Relevant log output

```shell

```

### Additional information

_No response_

### LINKED ISSUE #3567: [Bug]: Some freetext settings fields don't trigger the save or discard buttons.
### Contact Details

_No response_

### Checklist

- [x] I am able to reproduce the bug with the latest version.

- [x] I made sure that there are no existing **OPEN or CLOSED issues** which I could contribute my information to.

- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

- [x] This issue contains only one bug.

- [x] I have read and understood the **Contribution Guidelines**.

- [x] I agree to follow this project's Code of Conduct

### Affected app version

2.7.5

### Steps to reproduce the bug

| Page | Setting | 
| --- | --- | 
| LoRa| |
| Channels | | 
| Security | | 
| User | | 
| Device | |  
| Position | Fixed Position #3564 | 
| Power | | 
| External Notifications | Edit ringtone #3550 | 
| Canned Message | Messages #3549 |

@NeimadTL

### PR DESCRIPTION
**Pull request by mdecourcy**
**Text field save buttons:**
  - Add additionalDirtyCheck parameter to RadioConfigScreenList for tracking state changes outside the main ConfigState
  - Track changes to Position coordinates, External Notification ringtone, and Canned Messages separately from main config state
  - Move save/discard buttons inside LazyColumn to prevent overlapping content
  - Add onDiscard callback to reset additional state
  - Add onFocusChanged parameter to EditTextPreference Double overload

**Dropdown type mismatches:**
  - Fix External Notification "Nag Timeout" dropdown showing blank by converting Int to Long (.toLong()) to match dropdown item types
  - Fix External Notification "Output Duration" dropdown same issue
  - Both fields are uint32 in protobuf, dropdowns use Long values

**Missing LoRa setting:**
  - Add missing "Override Duty Cycle" checkbox to LoRa config between txEnabled and hopLimit fields
  - Field existed in protobuf and translations but was omitted from UI

**MQTT cloud icon display:**
  - Fix MQTT cloud icon not displaying correctly for messages via MQTT
  - Add viaMqtt field to DataPacket model to store packet's via_mqtt flag
  - Map packet.viaMqtt in MeshService.toDataPacket() from protobuf
  - Use data.viaMqtt instead of node.viaMqtt in Packet.toMessage()
  - Icon now shows when the specific message traveled via MQTT, not just when we've ever heard from that node via MQTT
  
  Closes #3434 
  Closes #3324
  Closes #3548
  Closes #3567

### CODE REVIEW

File: feature/settings/src/main/kotlin/org/meshtastic/feature/settings/radio/component/CannedMessageConfigItemList.kt [hunk 1]
```diff
@@ -72,6 +72,8 @@ fun CannedMessageConfigScreen(viewModel: RadioConfigViewModel = hiltViewModel(),
         enabled = state.connected,
         responseState = state.responseState,
         onDismissPacketResponse = viewModel::clearPacketResponse,
+        additionalDirtyCheck = { messagesInput != messages },
```
Comment (DaneEvans) [inline feature/settings/src/main/kotlin/org/meshtastic/feature/settings/radio/component/CannedMessageConfigItemList.kt:75]: 'dirty' ?

Comment (mdecourcy) [reply feature/settings/src/main/kotlin/org/meshtastic/feature/settings/radio/component/CannedMessageConfigItemList.kt:75]: Follows pattern in `RadioConfigScreenList.kt`: `ConfigState.isDirty`
