### PR TITLE
fix(compass): stop coarse network fixes from clobbering GPS fixes

### LINKED ISSUE #4864: [Bug]: Built-in compass jumps between 2 positions
### Contact Details

reply in this github issue...

### Checklist

- [x] I am able to reproduce the bug with the latest version.

- [ ] I have updated to the latest *Alpha* firmware, and am able to reproduce the bug. Many issues are fixed quickly in alpha before the general beta release. *From all i could tell, this is a app-exclusive issue, as the location is provided once by the packet and the compass only uses phone GNSS*

- [x] I made sure that there are no existing **OPEN or CLOSED issues** which I could contribute my information to.

- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

- [x] This issue contains only one bug.

- [x] I have read and understood the **Contribution Guidelines**.

- [x] I agree to follow this project's Code of Conduct

- [x] I actually read this list, and should be taken seriously.

### Affected app version

2.7.13 (29320069) fdroid

### Affected Android version

Android 16 (GrapheneOS)

### Affected phone model

Pixel 7 Pro

### Affected node model

Seeed Card Tracker T1000-E (tracker-t1000-e)

### Affected node firmware version

2.7.15

### Steps to reproduce the bug

1. Select a node in the nodes list
2. Click "Exchange" in the Position section.
3. Click "Open Compass"
4. Observe the distance measurement

### Actual behavior

The compass orientation and position jumps between a somewhat accurate distance and direction and a far-off distance and direction

### Expected behavior

The compass should use only the phones GNSS fix if it is available, and should be as accurate (distance and heading) as opening the position in a separate app, for example CoMaps.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/dcff1060-8177-4b07-84a4-888710d41581

### Relevant log output

Full log file, as exported by going to App Info > View Logs > save button [Meshtastic log a7927a3c970c.txt](https://github.com/user-attachments/files/26145106/Meshtastic.log.a7927a3c970c.txt). Contains multiple occurrences of the bug, for example at `03-20 15:41:38`

<details><summary>Excerpt of system log of viewing the compass at 15:41</summary>
<p>

03-20 15:41:38.045 radio  2425  2936 D SatelliteController: iisInCarrierRoamingNbIotNtn: satellite is disabled
03-20 15:41:38.052 10107  2397  2397 I SHANNON_IMS: 7261 [PROX] Received onSignalStrengthsChanged [CellSignalStrengthLte: rssi=-85 rsrp=-119 rsrq=-12 rssnr=-2 cqiTableIndex=1 cqi=3 ta=13 level=1 parametersUseForLevel=0] [SLID:0 APM:false] (ImsConnectivityProxyListener$ImsPhoneStateListener%onSignalStrengthsChanged:413)
03-20 15:41:38.053 radio  2425  2936 D SatelliteController: getCarrierRoamingNtnConnectType: Falling back to global carrier config connect type: 0
03-20 15:41:38.197  1000   624   643 E gralloc5: Producer and consumer not identified.
--------- switch to events
03-20 15:41:38.199  1000  1646  1995 I input_interaction: Interaction with: [651f1d0 com.geeksville.mesh/com.geeksville.mesh.MainActivity,PointerEventDispatcher0], on displayId 0
--------- switch to main
03-20 15:41:38.200 10105 15307 15307 D TaskbarManager: dispatchTouchEvent:  displayId=0 isDefaultDisplay=true
03-20 15:41:38.261  9999  2130  2132 I deeptouch: I0000 00:00:1774021298.261030    2132 tf_lite_classifier.cc:415] Event stream classified as kNone
03-20 15:41:38.264  1000   982   982 D usf_sensor_hal: rotation vector: Enter Batch. Period = 66667000, latency = 0.
03-20 15:41:38.265  1000   982   982 D usf_sensor_hal: rotation vector: Enter Activate. Enable = 1.
03-20 15:41:38.265  1000   982  1542 I sensor-suez: Vendor atom [id = 100243] reported.
03-20 15:41:38.266  root  1205  1205 D AOC     : A3:MSG: usf_sensor.cc, 1705: USF: Received start sampling request for Rotation Vector Sensor (active:1).
03-20 15:41:38.267  root  1205  1205 D AOC     : A3:MSG: vsc_sensor.cc, 37: VSC: [Rotation Vector Sensor] enable: period 66667000, latency = 0
03-20 15:41:38.267  root  1205  1205 D AOC     : A3:MSG: usf_vsc_log.cc, 44: USF: {Fusion} configure fusion 11 66667us 0us.
03-20 15:41:38.267  root  1205  1205 D AOC     : A3:MSG: vsc_controller.cc, 532: VSC: [Rotation Vector Sensor] requestSensorEvents: sensor 0x10001, period=66 latency=0
03-20 15:41:38.268  root  1205  1205 D AOC     : A3:MSG: usf_sensor.cc, 1705: USF: Received start sampling request for LSM6DSV Accelerometer (active:6).
03-20 15:41:38.271  root  1205  1205 D AOC     : A3:MSG: lsm6dsv_device.cc, 732: USF: Lsm6dsvDevice: Sensor 0: Enabled 1, odr_index 5, period_ns 20000000.
03-20 15:41:38.271  root  1205  1205 D AOC     : A3:MSG: lsm6dsv_fifo.cc, 755: USF: Lsm6dsvFifo: ODR: XL/G/T/TS: 60/60/15/7 WM: 4 Intr: 36.
03-20 15:41:38.272  root  1205  1205 D AOC     : A3:MSG: lsm6dsv_device.cc, 641: USF: Lsm6dsvDevice: Fifo was disabled for 746744ns.
03-20 15:41:38.274  root  1205  1205 D AOC     : A3:MSG: vsc_controller.cc, 532: VSC: [Rotation Vector Sensor] requestSensorEvents: sensor 0x10004, period=5 latency=0m
03-20 15:41:38.277  root  1205  1205 D AOC     : A3:MSG: usf_sensor.cc, 1705: USF: Received start sampling request for LSM6DSV Gyroscope (active:2).
03-20 15:41:38.278  root  1205  1205 D AOC     : A3:MSG: lsm6dsv_device.cc, 732: USF: Lsm6dsvDevice: Sensor 1: Enabled 1, odr_index 7, period_ns 5000000.
03-20 15:41:38.279  root  1205  1205 D AOC     : A3:MSG: lsm6dsv_fifo.cc, 755: USF: Lsm6dsvFifo: ODR: XL/G/T/TS: 60/240/15/30 WM: 1 Intr: 240.
03-20 15:41:38.279  root  1205  1205 D AOC     : A3:MSG: lsm6dsv_device.cc, 641: USF: Lsm6dsvDevice: Fifo was disabled for 667806ns.
03-20 15:41:38.280  root  1205  1205 D AOC     : A3:MSG: vsc_controller.cc, 532: VSC: [Rotation Vector Sensor] requestSensorEvents: sensor 0x10002, period=20 latency=0
03-20 15:41:38.281  root  1205  1205 D AOC     : A3:MSG: usf_sensor.cc, 1705: USF: Received start sampling request for Fusion Mag (active:2).
03-20 15:41:38.281  root  1205  1205 D AOC     : A3:MSG: fusion_mag_sensor.cc, 677: USF: FMAG: Reconfig sampling: period(new/old) = 20/100ms, latency = 0ms.
03-20 15:41:38.282   gps   995  1006 D GnssAidl: Gnss::setPositionMode
03-20 15:41:38.282   gps   995  1006 D GnssVisibilityControlAidl: GnssVisibilityControl::isInEmergencySession
03-20 15:41:38.283  root  1205  1205 D AOC     : A3:MSG: usf_sensor.cc, 1705: USF: Received start sampling request for MMC56X3X Magnetometer 0 (active:2).
03-20 15:41:38.283 10453 16716 16716 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): android.app.Dialog$$ExternalSyntheticLambda2@2d92a8
03-20 15:41:38.284  root  1205  1205 D AOC     : A3:MSG: vsc_controller.cc, 673: VSC: [Rotation Vector Sensor] requestSensorBiasEvents: sensor 0x10002, enable 1.
--------- switch to system
03-20 15:41:38.284  1000  1646  2005 D CoreBackPreview: Window{f7e1063 u0 com.geeksville.mesh/com.geeksville.mesh.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@d299651, mPriority=-1, mIsAnimationCallback=false, mOverrideBehavior=0}
--------- switch to main
03-20 15:41:38.284   gps   995  1006 I libgps  : [proxy__gnss_visibility_control_is_in_emergency_session_cb] = 0
03-20 15:41:38.284   gps  1173  1173 D gpsd    : WakeLock(Acquire,GPSD)
03-20 15:41:38.285   gps   995  1006 D GnssAidl: Gnss::start
03-20 15:41:38.285  1000   982  1542 I sensor-suez: Vendor atom [id = 100242] reported.
03-20 15:41:38.285  1000   982  1542 I sensor-suez: Vendor atom [id = 100243] reported.
03-20 15:41:38.285  root  1205  1205 D AOC     : A3:MSG: mmc56x3x_device.cc, 409: USF: MMC56X3X1: mmc56x3x_enable_measure odr = 50.
03-20 15:41:38.286 10453 16716 16716 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): androidx.navigationevent.OnBackInvokedInput$createOnBackAnimationCallback$1@69d086c
--------- switch to system
03-20 15:41:38.287  1000  1646  1956 D CoreBackPreview: Window{f7e1063 u0 com.geeksville.mesh/com.geeksville.mesh.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@a27deb6, mPriority=0, mIsAnimationCallback=true, mOverrideBehavior=0}
--------- switch to main
03-20 15:41:38.287  root  1205  1205 D AOC     : A3:MSG: usf_sensor.cc, 1705: USF: Received start sampling request for MMC56X3X Magnetometer 1 (active:2).
03-20 15:41:38.287  root  1205  1205 D AOC     : A3:MSG: mmc56x3x_device.cc, 409: USF: MMC56X3X2: mmc56x3x_enable_measure odr = 50.
03-20 15:41:38.287 10439 14870 14898 I HbmSvManager: LbeLux 5197 default
03-20 15:41:38.288 10439 14870 14898 D HbmSvManager: Ambient sensor :  TMD3719 Ambient Light update Lux : 5197.075
03-20 15:41:38.290   gps   995  1006 D GnssAidl: Gnss::injectTime
--------- switch to events
03-20 15:41:38.292  1000  1646  1754 I input_focus: [window=Focus request f7e1063 com.geeksville.mesh/com.geeksville.mesh.MainActivity,reason=reason=UpdateInputWindows]
--------- switch to main
03-20 15:41:38.299   gps   995  1006 D GnssAidl: Gnss::injectTime
--------- switch to events
03-20 15:41:38.300 10453 16716 16716 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
03-20 15:41:38.318  1000  1646  1995 I input_focus: [window=Focus leaving 651f1d0 com.geeksville.mesh/com.geeksville.mesh.MainActivity,reason=reason=Waiting for window because NO_WINDOW]
03-20 15:41:38.335  1000  1646  1995 I input_focus: [window=Focus entering f7e1063 com.geeksville.mesh/com.geeksville.mesh.MainActivity,reason=reason=Window became focusable. Previous reason: NOT_VISIBLE]
--------- switch to main
03-20 15:41:38.354  1000   982  1542 I sensor-suez: Vendor atom [id = 100245] reported.
03-20 15:41:38.357  1000  1646  2006 I ImeTracker: com.geeksville.mesh:d67dbba7: onRequestHide at ORIGIN_SERVER reason HIDE_UNSPECIFIED_WINDOW fromUser false
--------- switch to system
03-20 15:41:38.358 10453 16716 16716 D InsetsController: hide(ime())
--------- switch to main
03-20 15:41:38.358 10453 16716 16716 I ImeTracker: com.geeksville.mesh:d67dbba7: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
03-20 15:41:38.362  1000  1646  2005 I ImeTracker: system_server:279638ce: onRequestHide at ORIGIN_SERVER reason IME_REQUESTED_CHANGED_LISTENER fromUser false
03-20 15:41:38.363  1000  1646  1753 I ImeTracker: system_server:279638ce: onCancelled at PHASE_SERVER_SHOULD_HIDE
03-20 15:41:38.378 10138 13343  4981 I NearbyMediums: No BLE Fast/GATT advertisements found in the latest cycle.
03-20 15:41:38.378 10138 13343  4981 I NearbyMediums: Current Tracked Scanning Clients are : {NearbyConnections.EnvironmentMonitor, NearbySharing, NearbyConnections.TxAdvertisement}
03-20 15:41:38.439 10205   922  1068 D GeckoIdleService: Get idle time: time since reset 2901 msec
03-20 15:41:38.439 10205   922  1068 D GeckoIdleService: Idle timer callback: current idle time 2901 msec
03-20 15:41:38.439 10205   922  1068 D GeckoIdleService: next timeout 2099 msec from now
03-20 15:41:38.439 10205   922  1068 D GeckoIdleService: SetTimerExpiryIfBefore: next timeout 2099 msec from now
03-20 15:41:38.439 10205   922  1068 D GeckoIdleService: reset timer expiry to 2109 msec from now
03-20 15:41:38.538 10439 14870 14898 I HbmSvManager: LbeLux 5275 default
03-20 15:41:38.538 10439 14870 14898 D HbmSvManager: Ambient sensor :  TMD3719 Ambient Light update Lux : 5275.1206
--------- switch to events
03-20 15:41:38.728  1000  1646  1752 I commit_sys_config_file: [name=jobs,time=6ms]
--------- switch to main
03-20 15:41:38.790 10439 14870 14898 I HbmSvManager: LbeLux 5352 default
03-20 15:41:38.790 10439 14870 14898 D HbmSvManager: Ambient sensor :  TMD3719 Ambient Light update Lux : 5351.645
03-20 15:41:38.797   gps  1173  1173 D gpsd    : CALL_SENTRY(main()): GlEngine::OnStart took 502 ms (from 23430882 to 23431384) (logOverhead=0,0,0,0,0,0,0), start: 16:41:38.295
03-20 15:41:38.809   gps  1173  1173 D gpsd    : CALL_SENTRY(main()): marshal_gps_start took 524 ms (from 23430872 to 23431396) (logOverhead=0,0,0,0,0,0,0), start: 16:41:38.285
03-20 15:41:38.810   gps  1173  1173 D gpsd    : CALL_SENTRY(main()): ProcessEvent took 524 ms (from 23430872 to 23431396) (logOverhead=0,0,0,0,0,0,0), start: 16:41:38.286
03-20 15:41:38.810  1000  1646  7899 D AGnssRilCbJni: requestSetIdCb. setIdflag: 1, 
03-20 15:41:38.810   gps  1173  1173 I LibSITRil-Gps: RequestAGPS: msgId=231 data=0xe41620001a70 data_len=1 callback=0xc8aacaffb574
03-20 15:41:38.810   gps  1173  1173 D RILClient: [OemClient] RILC_Send msgId:231 lengh:1 channel:0
03-20 15:41:38.810   gps  1173  1173 D RILClient: [OemClient]REQ (clientId = 1, t = 95, msgId = 231, len = 1 channel = 0)
03-20 15:41:38.814   gps  1173  2095 D RILClient: [OemClient]RSP: (clientId = 1, t = 95, msgId = 231, len = 0, channel = 0, status = 0)
03-20 15:41:39.019  1000  1646  7899 D WifiNl80211Manager: Scan result ready event
03-20 15:41:39.019  1000  1646  7899 D WifiNative: Scan result ready event
03-20 15:41:39.024  wifi  1022  1072 I WifiHAL : Creating message to get link statistics; iface = 48
03-20 15:41:39.041 10439 14870 14898 I HbmSvManager: LbeLux 5427 default
03-20 15:41:39.041 10439 14870 14898 D HbmSvManager: Ambient sensor :  TMD3719 Ambient Light update Lux : 5426.648
03-20 15:41:39.073  wifi  1022  2491 D WifiHAL : Start debug command: mType GET_FEATURE
03-20 15:41:39.073  wifi  1022  2491 I WifiHAL : CreateRequest mType = GET_FEATURE
03-20 15:41:39.073  wifi  1022  2491 D WifiHAL : In DebugCommand::handleResponse, mType:GET_FEATURE
03-20 15:41:39.073  wifi  1022  2491 D WifiHAL : len = 4, expected len = 4
03-20 15:41:39.291 10439 14870 14898 I HbmSvManager: LbeLux 5500 default
03-20 15:41:39.292 10439 14870 14898 D HbmSvManager: Ambient sensor :  TMD3719 Ambient Light update Lux : 5500.129
03-20 15:41:39.317   gps  1173  1173 D gpsd    : $PGLOR,0,RID,4776,154,20,24,625212*33\r
03-20 15:41:39.324  1000   982   982 D usf_sensor_hal: accelerometer: Enter Batch. Period = 20000000, latency = 0.
03-20 15:41:39.324  1000   982   982 D usf_sensor_hal: IMU temperature: Enter Batch. Period = 533334000, latency = 0.
03-20 15:41:39.325  1000   982  1424 D usf_sensor_hal: accelerometer: Enter Activate. Enable = 1.
03-20 15:41:39.325  1000   982  1542 I sensor-suez: Vendor atom [id = 100243] reported.
03-20 15:41:39.325  root  1205  1205 D AOC     : A3:MSG: usf_sensor.cc, 1705: USF: Received start sampling request for LSM6DSV Accelerometer (active:6).
03-20 15:41:39.326  root  1205  1205 D AOC     : A3:MSG: lsm6dsv_device.cc, 732: USF: Lsm6dsvDevice: Sensor 0: Enabled 1, odr_index 5, period_ns 20000000.
03-20 15:41:39.326  root  1205  1205 D AOC     : A3:MSG: lsm6dsv_fifo.cc, 755: USF: Lsm6dsvFifo: ODR: XL/G/T/TS: 60/240/15/30 WM: 1 Intr: 240.
03-20 15:41:39.326  root  1205  1205 D AOC     : A3:MSG: lsm6dsv_device.cc, 641: USF: Lsm6dsvDevice: Fifo was disabled for 202840ns.
03-20 15:41:39.328  1000   982  1542 I sensor-suez: Vendor atom [id = 100242] reported.
03-20 15:41:39.328  1000   982  1542 I sensor-suez: Vendor atom [id = 100243] reported.
03-20 15:41:39.328  1000   982  1424 D usf_sensor_hal: gyroscope: Enter Batch. Period = 20000000, latency = 0.
03-20 15:41:39.328  1000   982  1424 D usf_sensor_hal: IMU temperature: Enter Batch. Period = 533334000, latency = 0.
03-20 15:41:39.329  1000   982  1424 D usf_sensor_hal: gyroscope: Enter Activate. Enable = 1.
03-20 15:41:39.328  1000   982  1542 I sensor-suez: Vendor atom [id = 100243] reported.
03-20 15:41:39.330  root  1205  1205 D AOC     : A3:MSG: usf_sensor.cc, 1705: USF: Received start sampling request for LSM6DSV Gyroscope (active:3).
03-20 15:41:39.331  1000   982  1542 I sensor-suez: Vendor atom [id = 100242] reported.
03-20 15:41:39.332  1000   982  1542 I sensor-suez: Vendor atom [id = 100243] reported.
03-20 15:41:39.333  1000   982  1424 D usf_sensor_hal: pressure: Enter Batch. Period = 100000000, latency = 0.
03-20 15:41:39.333  1000   982  1424 D usf_sensor_hal: pressure: Enter Activate. Enable = 1.
03-20 15:41:39.333  1000   982  1542 I sensor-suez: Vendor atom [id = 100243] reported.
03-20 15:41:39.334  root  1205  1205 D AOC     : A3:MSG: usf_sensor.cc, 1705: USF: Received start sampling request for ICP20100 Pressure Sensor (active:2).
03-20 15:41:39.334  root  1205  1205 D AOC     : A3:MSG: icp20100_device.cc, 146: USF: ICP20100: Barometer starts sampling: period_ns = 40000000, max_latency_ns = 1000
03-20 15:41:39.336  1000   982  1542 I sensor-suez: Vendor atom [id = 100245] reported.
03-20 15:41:39.337  1000   982  1542 I sensor-suez: Vendor atom [id = 100242] reported.
03-20 15:41:39.337  1000   982  1542 I sensor-suez: Vendor atom [id = 100243] reported.
03-20 15:41:39.353  1000   982  1542 I sensor-suez: Vendor atom [id = 100245] reported.
03-20 15:41:39.367  root  1205  1205 D AOC     : A3:MSG: icp20100_device.cc, 520: USF: ICP20100: Waiting for mode sync bit ready (0/10).
03-20 15:41:39.430  1000   982  1542 I sensor-suez: Vendor atom [id = 100245] reported.
03-20 15:41:40.189  1000   624   643 E gralloc5: Producer and consumer not identified.
--------- switch to events
03-20 15:41:40.191  1000  1646  1995 I input_interaction: Interaction with: [f7e1063 com.geeksville.mesh/com.geeksville.mesh.MainActivity,PointerEventDispatcher0], on displayId 0
--------- switch to main
03-20 15:41:40.191 10105 15307 15307 D TaskbarManager: dispatchTouchEvent:  displayId=0 isDefaultDisplay=true
03-20 15:41:40.548 10205   922  1068 D GeckoIdleService: Get idle time: time since reset 5010 msec
03-20 15:41:40.548 10205   922  1068 D GeckoIdleService: Idle timer callback: current idle time 5010 msec
03-20 15:41:40.548 10205   922  1068 D GeckoIdleService: next timeout 294989 msec from now
03-20 15:41:40.549 10205   922  1068 D GeckoIdleService: SetTimerExpiryIfBefore: next timeout 294989 msec from now
03-20 15:41:40.549 10205   922  1068 D GeckoIdleService: reset timer expiry to 294999 msec from now
03-20 15:41:40.549 10205   922  1068 D GeckoIdleService: Idle timer callback: tell observer 0xcd07c04a47c8 user is idle
--------- switch to system
03-20 15:41:40.655  1000  1646  1753 W AccessibilityWindowsPopulator: Windows change within in 2 frames continuously over 500 ms and notify windows changed immediately
--------- switch to main
03-20 15:41:40.690  9999  2130  2132 I deeptouch: I0000 00:00:1774021300.690634    2132 tf_lite_classifier.cc:415] Event stream classified as kNone

</p>
</details>

### Additional information

- GrapheneOS
- Location services: Wi-Fi scanning enabled, Bluetooth scanning enabled, Network location: GrapheneOS Appl proxy, Geocoder disabled
- I don't have any issues of this sort in other location-based apps (CoMaps, StreetComplete, OsmAnd, GPSTest)
- I have "provide phone location to mesh" disabled
- I have set animation scale to play twice as fast

### PR DESCRIPTION
**Pull request by jamesarich**
## Summary

The compass distance and bearing jumped between two positions because `AndroidPhoneLocationProvider` subscribes to both `GPS_PROVIDER` and `NETWORK_PROVIDER` and unconditionally replaced `lastLocation` on every callback. A coarse Wi-Fi/cell triangulation fix would overwrite a fresh high-accuracy GPS fix (and vice versa), causing the visible jitter.

The reporter confirmed the symptom disappears when network location is disabled, which matches this diagnosis exactly.

## Changes

- Added the canonical Android `isBetterLocation` comparison (significantly-newer / accuracy / same-provider rules).
- Applied it to live `onLocationChanged` callbacks **and** to the initial `getLastKnownLocation` reduction so the bootstrap fix is also chosen sensibly.
- Network fixes are still used as a fallback when no recent GPS fix is available, so devices without GPS still work.

Closes #4864

### CODE REVIEW

File: feature/node/src/androidMain/kotlin/org/meshtastic/feature/node/compass/AndroidPhoneLocationProvider.kt [hunk 1]
```diff
@@ -124,5 +134,41 @@ class AndroidPhoneLocationProvider(private val context: Context, private val dis
...
+         * coarse Wi-Fi/cell fixes to overwrite recent fine GPS fixes, making the compass distance and bearing jump
+         * between two positions (issue #4864).
+         */
+        @Suppress("ReturnCount")
+        internal fun isBetterLocation(candidate: Location, current: Location?): Boolean {
+            if (current == null) return true
+
+            val timeDelta = candidate.time - current.time
+            val isSignificantlyNewer = timeDelta > SIGNIFICANTLY_NEWER_MS
+            val isSignificantlyOlder = timeDelta < -SIGNIFICANTLY_NEWER_MS
```
Comment (laundmo) [inline feature/node/src/androidMain/kotlin/org/meshtastic/feature/node/compass/AndroidPhoneLocationProvider.kt:152]: i think these variables are redundant, or at least confusingly named

File: feature/node/src/androidMain/kotlin/org/meshtastic/feature/node/compass/AndroidPhoneLocationProvider.kt [hunk 2]
```diff
@@ -124,5 +134,41 @@ class AndroidPhoneLocationProvider(private val context: Context, private val dis
...
+            val isNewer = timeDelta > 0
+
+            // A much newer fix is always preferred even if accuracy is worse — the device
+            // has likely moved, so a stale "accurate" fix is worse than a fresh coarse one.
+            if (isSignificantlyNewer) return true
+            if (isSignificantlyOlder) return false
+
+            val accuracyDelta = candidate.accuracy - current.accuracy
+            val isMoreAccurate = accuracyDelta < 0f
+            val isLessAccurate = accuracyDelta > 0f
```
Comment (laundmo) [inline feature/node/src/androidMain/kotlin/org/meshtastic/feature/node/compass/AndroidPhoneLocationProvider.kt:162]: again, redundant checks

File: feature/node/src/androidMain/kotlin/org/meshtastic/feature/node/compass/AndroidPhoneLocationProvider.kt [hunk 3]
```diff
@@ -124,5 +134,41 @@ class AndroidPhoneLocationProvider(private val context: Context, private val dis
...
+            val isSignificantlyLessAccurate = accuracyDelta > SIGNIFICANTLY_LESS_ACCURATE_M
+            val isFromSameProvider = candidate.provider == current.provider
+
+            return when {
+                isMoreAccurate -> true
+                isNewer && !isLessAccurate -> true
+                isNewer && !isSignificantlyLessAccurate && isFromSameProvider -> true
+                else -> false
+            }
```
Comment (laundmo) [inline feature/node/src/androidMain/kotlin/org/meshtastic/feature/node/compass/AndroidPhoneLocationProvider.kt:171]: explicitly returning a boolean by matching over a boolean...
could just do `return isMoreAccurate || (isNewer && !isLessAccurate) || (isNewer && isSignificantlyLessAccurate && isFromSameProvider)`

**Review by laundmo — COMMENTED** [review]
some... strange decisions here

**Comment by jamesarich** [comment]
@laundmo feel free to open a refactor pr, but this does what it says on the box and follows platform recommendations in a readable fashion.

**Comment by laundmo** [comment]
I'm not going to set up a whole android development environment just to correct what i suspect is LLM-generated code.

if this is the kind of code you want in the repo, thats your decision as a maintainer and shows how much a PR like that would be appreciated (not at all).
tho i should have suspected feedback is not something remotely desired, what with the pr being merged immediately after being created.

**Comment by jamesarich** [comment]
> I'm not going to set up a whole android development environment just to correct what i suspect is LLM-generated code.

Complaining _is_ easier for sure.

> the pr being merged immediately after being created

As the maintainer (and currently solo contributor), I tend to move pretty quickly.

**Comment by laundmo** [comment]
> currently solo contributor

what i've seen of this repo doesn't make me *want* to become a contributor, thats part of my point. I mean, android development being how it is also doesn't make me want to contribute, but google is to blame for that, not you.

**Comment by DaneEvans** [comment]
When you see the users, you'll be even less inclined.  

Honestly we'd love someone inclined to refactor things down and improve areas, but they also need to be a contributor and able to communicate.
