### PR TITLE
fix #3838 : message deletion count on the contacts page.

### LINKED ISSUE #3838: [Bug]: Delete messages popup missing number
### Contact Details

Stary2001 on discord

### Checklist

- [x] I am able to reproduce the bug with the latest version.

- [x] I have updated to the latest *Alpha* firmware, and am able to reproduce the bug. Many issues are fixed quickly in alpha before the general beta release.

- [x] I made sure that there are no existing **OPEN or CLOSED issues** which I could contribute my information to.

- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

- [x] This issue contains only one bug.

- [x] I have read and understood the **Contribution Guidelines**.

- [x] I agree to follow this project's Code of Conduct

- [x] I actually read this list, and should be taken seriously.

### Affected app version

2.7.8 google

### Affected Android version

Android 16

### Affected phone model

Pixel 7a

### Affected node model

T1000E

### Affected node firmware version

2.7.13

### Steps to reproduce the bug

Go to Conversations tab, select a DM/channel, press delete.

### Actual behavior

Number of messages is not shown.

### Expected behavior

Number of messages to delete is shown.

### Screenshots/Screen recordings

Image

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DaneEvans**
closes #3838

### CODE REVIEW

File: app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt [hunk 1]
```diff
@@ -393,12 +397,16 @@ private fun DeleteConfirmationDialog(
     onDismiss: () -> Unit,
     onConfirm: () -> Unit, // Lambda to handle the delete action
 ) {
+    // Log the selectedCount for debugging purposes
+    androidx.compose.runtime.LaunchedEffect(selectedCount) {
+        android.util.Log.d("DeleteConfirmationDialog", "Selected count for deletion: $selectedCount")
```
Comment (jamesarich) [inline app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt]: Timber or clean up
