### PR TITLE
fix: address backfill issue on tcp connections; add logging

### LINKED ISSUE #3672: [Bug]: Network (TCP/WIFI) losing packets when disconnected and reconnected in v2.7.6-open.4
### Contact Details

discord: corruptedstack

### Checklist

- [x] I am able to reproduce the bug with the latest version.

- [x] I made sure that there are no existing **OPEN or CLOSED issues** which I could contribute my information to.

- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

- [x] This issue contains only one bug.

- [x] I have read and understood the **Contribution Guidelines**.

- [x] I agree to follow this project's Code of Conduct

### Affected app version

v2.7.6-open.4 (29319372)

### Affected Android version

Android 16 October 5th Security Update

### Affected phone model

Pixel 10 Pro XL, Pixel 9, Oneplus 13

### Affected node model

Native (meshtasticd), heltec v4 (connected to wifi), station g2 (connected to wifi)

### Affected node firmware version

2.7.13

### Steps to reproduce the bug

1. Connect to a Network Node (TCP/WIFI) under Network Tab
2. Disconnect
3. Send some packets to the node through another device, or allow packets to be rxed, specifically text message packets
4. Reconnect

### Actual behavior

No messages arrive, no packets appeared to processed. Nodelist is fine. 

### Expected behavior

All messages/packets in queue on device are delivered and viewable under messages on reconnect. 

### Screenshots/Screen recordings

_No response_

### Relevant log output

```shell
Logcat after reconnecting:
11-11 11:50:21.667 30157 30378 E AndroidRuntime: Process: com.geeksville.mesh, PID: 30157
11-11 21:49:52.713  2045  3323 V WindowManager: DesktopModeLaunchParamsModifier: phase= 0 task=null activity=ActivityRecord{162233374 u0 com.geeksville.mesh/.MainActivity display-from-option=0 display-id=0 task-display-area-windowing-mode=1 suggested-display-area=DefaultTaskDisplayArea@111705726 task null, skipping
11-11 21:49:52.713  2045  3323 V WindowManager: TaskLaunchParamsModifier:phase=0 task=null activity=ActivityRecord{162233374 u0 com.geeksville.mesh/.MainActivity t-1} display-from-option=0 display-id=0 task-display-area-windowing-mode=1 suggested-display-area=DefaultTaskDisplayArea@111705726
11-11 21:49:52.713  2045  3323 V WindowManager: DesktopModeLaunchParamsModifier: phase= 3 task=Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh} activity=ActivityRecord{162233374 u0 com.geeksville.mesh/.MainActivity t-1} display-from-option=0 display-id=0 task-display-area-windowing-mode=1 suggested-display-area=DefaultTaskDisplayArea@111705726 not entering desktop mode, skipping
11-11 21:49:52.713  2045  3323 V WindowManager: TaskLaunchParamsModifier:phase=3 task=Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh} activity=ActivityRecord{162233374 u0 com.geeksville.mesh/.MainActivity t-1} display-from-option=0 display-id=0 task-display-area-windowing-mode=1 suggested-display-area=DefaultTaskDisplayArea@111705726 inherit-from-source=fullscreen non-freeform-task-display-area display-area=DefaultTaskDisplayArea@111705726 default-portrait freeform-size-mismatch=Rect(336, 870 - 1009, 2214)
11-11 21:49:52.714  2045  3323 V WindowManager: DesktopModeLaunchParamsModifier: phase= 3 task=Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh} activity=ActivityRecord{162233374 u0 com.geeksville.mesh/.MainActivity t-1} display-from-option=0 display-id=0 task-display-area-windowing-mode=1 suggested-display-area=DefaultTaskDisplayArea@111705726 not entering desktop mode, skipping
11-11 21:49:52.714  2045  3323 V WindowManager: TaskLaunchParamsModifier:phase=3 task=Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh} activity=ActivityRecord{162233374 u0 com.geeksville.mesh/.MainActivity t-1} display-from-option=0 display-id=0 task-display-area-windowing-mode=1 suggested-display-area=DefaultTaskDisplayArea@111705726 inherit-from-source=fullscreen non-freeform-task-display-area display-area=DefaultTaskDisplayArea@111705726 default-portrait freeform-size-mismatch=Rect(336, 870 - 1009, 2214)
11-11 21:49:52.716  2045  3323 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 xflg=0x4 cmp=com.geeksville.mesh/.MainActivity bnds=[37,515][291,799]} with LAUNCH_SINGLE_TOP from uid 10254 (com.google.android.apps.nexuslauncher) (sr=3721734) (BAL_ALLOW_VISIBLE_WINDOW) result code=2
11-11 21:49:52.718  3251  3296 V WindowManagerShell: Transition requested (#3934): android.os.BinderProxy@ead3559 TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=8415 effectiveUid=10476 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.geeksville.mesh/.MainActivity } baseActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} topActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} origActivity=null realActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} numActivities=1 lastActiveTime=202350850 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.os.BinderProxy@3ba03} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 200 - 0, 0) topActivityInfo=ActivityInfo{1d7051e com.geeksville.mesh.MainActivity} launchCookies=[android.os.BinderProxy@f5081ff] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isTopActivityNoDisplay=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false isActivityStackTransparent=false lastNonFullscreenBounds=Rect(336, 870 - 1009, 2214) capturedLink=null capturedLinkTimestamp=0 requestedVisibleTypes=-9 topActivityRequestOpenInBrowserEducationTimestamp=0 appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false eligibleForLetterboxEducation= false isLetterboxEducationEnabled= false isLetterboxDoubleTapEnabled= false eligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 topActivityAppBounds=Rect(0, 0 - 1344, 2992) isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false hasMinAspectRatioOverride=false topActivityLetterboxBounds=null cameraCompatTaskInfo=CameraCompatTaskInfo { freeformCameraCompatMode=inactiveundefined} topNonResizableActivityAspectRatio=-1.0} topActivityMainWindowFrame=null isAppBubble=false}, pipChange = null, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@71d3bcc, appThread = android.app.IApplicationThread$Stub$Proxy@b72ce15, debugName = QuickstepLaunch }, displayChange = null, flags = 0, debugId = 3934 }
11-11 21:49:52.719  3251  3296 D WindowManagerShell: onActivityRestartAttempt: topActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity}, wasVisible=false
11-11 21:49:52.727  2045  3531 D CoreBackPreview: Window{6d75f3 u0 com.geeksville.mesh/com.geeksville.mesh.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@47a8991, mPriority=0, mIsAnimationCallback=true, mOverrideBehavior=0}
11-11 21:49:52.730  2045  2115 V WindowManager: Sent Transition (#3934) createdAt=11-11 21:49:52.713 via request=TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=8415 effectiveUid=10476 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.geeksville.mesh/.MainActivity } baseActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} topActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} origActivity=null realActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} numActivities=1 lastActiveTime=202350850 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{1ad43b6 Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 200 - 0, 0) topActivityInfo=ActivityInfo{6e5ff00 com.geeksville.mesh.MainActivity} launchCookies=[android.os.BinderProxy@a1bcf7] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isTopActivityNoDisplay=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false isActivityStackTransparent=false lastNonFullscreenBounds=Rect(336, 870 - 1009, 2214) capturedLink=null capturedLinkTimestamp=0 requestedVisibleTypes=-9 topActivityRequestOpenInBrowserEducationTimestamp=0 appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false eligibleForLetterboxEducation= false isLetterboxEducationEnabled= false isLetterboxDoubleTapEnabled= false eligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 topActivityAppBounds=Rect(0, 0 - 1344, 2992) isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false hasMinAspectRatioOverride=false topActivityLetterboxBounds=null cameraCompatTaskInfo=CameraCompatTaskInfo { freeformCameraCompatMode=inactiveundefined} topNonResizableActivityAspectRatio=-1.0} topActivityMainWindowFrame=null isAppBubble=false}, pipChange = null, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@a7ae764, appThread = android.app.IApplicationThread$Stub$Proxy@42d2dcd, debugName = QuickstepLaunch }, displayChange = null, flags = 0, debugId = 3934 }
11-11 21:49:52.731  2045  2115 V WindowManager:         {WCT{RemoteToken{1ad43b6 Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh}}} m=TO_FRONT f=MOVE_TO_TOP leash=Surface(name=Task=8415)/@0x2ff238c sb=Rect(0, 0 - 1344, 2992) eb=Rect(0, 0 - 1344, 2992) epz=Point(1344, 2992) d=0 taskParent=-1 winMode=1},
11-11 21:49:52.823  2045  3950 W PackageConfigPersister: App-specific configuration not found for packageName: com.geeksville.mesh and userId: 0
11-11 21:49:52.887  2045  2942 D CoreBackPreview: Window{6d75f3 u0 com.geeksville.mesh/com.geeksville.mesh.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@c123432, mPriority=0, mIsAnimationCallback=true, mOverrideBehavior=0}
11-11 21:49:52.888  2045  3950 D CoreBackPreview: Window{6d75f3 u0 com.geeksville.mesh/com.geeksville.mesh.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@53a583, mPriority=0, mIsAnimationCallback=true, mOverrideBehavior=0}
11-11 21:49:55.576  2045  5918 W ForegroundServiceTypeLoggerModule: Logger should be tracking FGS types correctly for UID 10476 in package com.geeksville.mesh
11-11 21:49:55.576  2045  5918 W ForegroundServiceTypeLoggerModule: Logger should be tracking FGS types correctly for UID 10476 in package com.geeksville.mesh
11-11 21:49:55.576  2045  5918 W ForegroundServiceTypeLoggerModule: Logger should be tracking FGS types correctly for UID 10476 in package com.geeksville.mesh
11-11 21:49:55.576  2045  5918 W ForegroundServiceTypeLoggerModule: Logger should be tracking FGS types correctly for UID 10476 in package com.geeksville.mesh
11-11 21:49:55.772  2045  2045 I NotificationService: Cannot find enqueued record for key: 0|com.geeksville.mesh|101|null|10476
11-11 21:49:55.798  2045  2045 I NotificationService: Cannot find enqueued record for key: 0|com.geeksville.mesh|101|null|10476
11-11 21:49:55.806  2045  2045 I NotificationService: Cannot find enqueued record for key: 0|com.geeksville.mesh|101|null|10476
11-11 21:50:57.573  2045  3944 I ActivityManager: Background started FGS: Allowed [callingPackage: com.geeksville.mesh; callingUid: 10476; uidState: TOP ; uidBFSL: [BFSL]; intent: Intent { xflg=0x4 cmp=com.geeksville.mesh/.service.MeshService }; code:PROC_STATE_TOP; tempAllowListReason:<null>; allowWiu:12; targetSdkVersion:36; callerTargetSdkVersion:36; startForegroundCount:9; bindFromPackage:null: isBindService:false]
11-11 21:51:16.752  2045  2115 V WindowManager:         {WCT{RemoteToken{1ad43b6 Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh}}} m=TO_BACK f=NONE leash=Surface(name=Task=8415)/@0x2ff238c sb=Rect(0, 0 - 1344, 2992) eb=Rect(0, 0 - 1344, 2992) epz=Point(1344, 2992) d=0 taskParent=-1 winMode=1},
11-11 21:51:18.290  2045  2115 V WindowManager:         {WCT{RemoteToken{1ad43b6 Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh}}} m=TO_BACK f=NONE leash=Surface(name=Task=8415)/@0x2ff238c sb=Rect(0, 0 - 1344, 2992) eb=Rect(0, 0 - 1344, 2992) epz=Point(1344, 2992) d=0 taskParent=-1 winMode=1},
11-11 21:51:18.671  2045  3944 D CoreBackPreview: Window{6d75f3 u0 com.geeksville.mesh/com.geeksville.mesh.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@afb5cfe, mPriority=-1, mIsAnimationCallback=false, mOverrideBehavior=0}
11-11 21:55:52.949 10260 10260 I NotificationListener: Handling notification state refresh for com.geeksville.mesh#0
11-11 21:55:52.949 10260 10260 I NotificationListener: Handling notification state refresh for com.geeksville.mesh#0
11-11 21:55:58.361 10260 10260 I NotificationListener: Handling notification state refresh for com.geeksville.mesh#0
11-11 21:55:58.361 10260 10260 I NotificationListener: Handling notification state refresh for com.geeksville.mesh#0
11-11 21:55:59.458  3251  3296 V WindowManagerShell: Transition requested (#3955): android.os.BinderProxy@7e9abee TransitionRequestInfo { type = TO_FRONT, triggerTask = TaskInfo{userId=0 taskId=8415 effectiveUid=10476 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.geeksville.mesh/.MainActivity } baseActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} topActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} origActivity=null realActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} numActivities=1 lastActiveTime=202535860 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.os.BinderProxy@3ba03} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 200 - 0, 0) topActivityInfo=ActivityInfo{8f4e88f com.geeksville.mesh.MainActivity} launchCookies=[android.os.BinderProxy@f5081ff] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isTopActivityNoDisplay=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false isActivityStackTransparent=false lastNonFullscreenBounds=Rect(336, 870 - 1009, 2214) capturedLink=null capturedLinkTimestamp=0 requestedVisibleTypes=-9 topActivityRequestOpenInBrowserEducationTimestamp=0 appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false eligibleForLetterboxEducation= false isLetterboxEducationEnabled= false isLetterboxDoubleTapEnabled= false eligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 topActivityAppBounds=Rect(0, 0 - 1344, 2992) isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false hasMinAspectRatioOverride=false topActivityLetterboxBounds=null cameraCompatTaskInfo=CameraCompatTaskInfo { freeformCameraCompatMode=inactiveundefined} topNonResizableActivityAspectRatio=-1.0} topActivityMainWindowFrame=null isAppBubble=false}, pipChange = null, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@cbcc71c, appThread = android.app.IApplicationThread$Stub$Proxy@cb37f25, debugName = QuickstepLaunch }, displayChange = null, flags = 0, debugId = 3955 }
11-11 21:55:59.460  3251  3296 D WindowManagerShell: onActivityRestartAttempt: topActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity}, wasVisible=false
11-11 21:55:59.492  2045  2115 V WindowManager: Sent Transition (#3955) createdAt=11-11 21:55:59.454 via request=TransitionRequestInfo { type = TO_FRONT, triggerTask = TaskInfo{userId=0 taskId=8415 effectiveUid=10476 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.geeksville.mesh/.MainActivity } baseActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} topActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} origActivity=null realActivity=ComponentInfo{com.geeksville.mesh/com.geeksville.mesh.MainActivity} numActivities=1 lastActiveTime=202535860 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{1ad43b6 Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 200 - 0, 0) topActivityInfo=ActivityInfo{6e5ff00 com.geeksville.mesh.MainActivity} launchCookies=[android.os.BinderProxy@a1bcf7] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isTopActivityNoDisplay=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false isActivityStackTransparent=false lastNonFullscreenBounds=Rect(336, 870 - 1009, 2214) capturedLink=null capturedLinkTimestamp=0 requestedVisibleTypes=-9 topActivityRequestOpenInBrowserEducationTimestamp=0 appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false eligibleForLetterboxEducation= false isLetterboxEducationEnabled= false isLetterboxDoubleTapEnabled= false eligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 topActivityAppBounds=Rect(0, 0 - 1344, 2992) isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false hasMinAspectRatioOverride=false topActivityLetterboxBounds=null cameraCompatTaskInfo=CameraCompatTaskInfo { freeformCameraCompatMode=inactiveundefined} topNonResizableActivityAspectRatio=-1.0} topActivityMainWindowFrame=null isAppBubble=false}, pipChange = null, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@c51969a, appThread = android.app.IApplicationThread$Stub$Proxy@fbc3bcb, debugName = QuickstepLaunch }, displayChange = null, flags = 0, debugId = 3955 }
11-11 21:55:59.492  2045  6473 D CoreBackPreview: Window{6d75f3 u0 com.geeksville.mesh/com.geeksville.mesh.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@75f7fa8, mPriority=0, mIsAnimationCallback=true, mOverrideBehavior=0}
11-11 21:55:59.492  2045  2115 V WindowManager:         {WCT{RemoteToken{1ad43b6 Task{543c2d7 #8415 type=standard A=10476:com.geeksville.mesh}}} m=TO_FRONT f=MOVE_TO_TOP leash=Surface(name=Task=8415)/@0x2ff238c sb=Rect(0, 0 - 1344, 2992) eb=Rect(0, 0 - 1344, 2992) epz=Point(1344, 2992) d=0 taskParent=-1 winMode=1},
11-11 21:55:59.534  2045  3002 I ImeTracker: com.geeksville.mesh:cf4c4ee: onRequestHide at ORIGIN_SERVER reason HIDE_UNSPECIFIED_WINDOW fromUser false
11-11 21:55:59.535 23630 23630 I ImeTracker: com.geeksville.mesh:cf4c4ee: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
11-11 21:55:59.537  9227  9227 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1347 onStartInput(EditorInfo{EditorInfo{packageName=com.geeksville.mesh, inputType=0, inputTypeString=NULL, enableLearning=false, autoCorrection=false, autoComplete=false, imeOptions=0, privateImeOptions=null, actionName=UNSPECIFIED, actionLabel=null, initialSelStart=-1, initialSelEnd=-1, initialCapsMode=0, label=null, fieldId=0, fieldName=null, extras=null, hintText=null, hintLocales=[]}}, false)
11-11 21:55:59.539  2045  3941 W PackageConfigPersister: App-specific configuration not found for packageName: com.geeksville.mesh and userId: 0
11-11 21:55:59.763 10260 10260 I NotificationListener: received notification posted event - com.geeksville.mesh#UserHandle{0},category=-1
11-11 21:55:59.764  6162  6997 I NotificationPipeline: Processing new notification: 0|com.geeksville.mesh|101|null|10476
11-11 21:55:59.765  6162  6997 I NotificationPipeline: parseAndSendNotification: 0|com.geeksville.mesh|101|null|10476, behavior=DEFAULT
11-11 21:55:59.771  6162  6997 I NotificationFilterModel: 0|com.geeksville.mesh|101|null|10476 filtered for reason: NON_CLEARABLE_NOTIFICATION
11-11 21:55:59.771  6162  6997 I NotificationPipeline: Processing new notification: 0|com.geeksville.mesh|101|null|10476
11-11 21:55:59.771  6162  6997 I NotificationPipeline: parseAndSendNotification: 0|com.geeksville.mesh|101|null|10476, behavior=DEFAULT
11-11 21:55:59.774  6162  6997 I NotificationFilterModel: 0|com.geeksville.mesh|101|null|10476 filtered for reason: NON_CLEARABLE_NOTIFICATION
11-11 21:55:59.780 10260 10260 I NotificationListener: received notification posted event - com.geeksville.mesh#UserHandle{0},category=-1
11-11 21:56:01.040  2045  3531 W ForegroundServiceTypeLoggerModule: Logger should be tracking FGS types correctly for UID 10476 in package com.geeksville.mesh
11-11 21:56:01.040  2045  3531 W ForegroundServiceTypeLoggerModule: Logger should be tracking FGS types correctly for UID 10476 in package com.geeksville.mesh
11-11 21:56:01.040  2045  3531 W ForegroundServiceTypeLoggerModule: Logger should be tracking FGS types correctly for UID 10476 in package com.geeksville.mesh
11-11 21:56:01.040  2045  3531 W ForegroundServiceTypeLoggerModule: Logger should be tracking FGS types correctly for UID 10476 in package com.geeksville.mesh
11-11 21:56:01.042  6162  6997 I NotificationPipeline: Processing notification dismissal on phone: 0|com.geeksville.mesh|706835373|null|10476
11-11 21:56:01.042  6162  6997 I NotifDismissalHandler: Notification 0|com.geeksville.mesh|706835373|null|10476 dismissed on phone, deleting data item /bridger/stream_item:9ab4bedf:com.geeksville.mesh:706835373:null_tag:0~7Ccom.geeksville.mesh~7C706835373~7Cnull~7C10476
11-11 21:56:01.052 10260 10260 I NotificationListener: received notification removed event - com.geeksville.mesh#UserHandle{0},category=-1
11-11 21:56:01.087 10260 10260 I NotificationListener: received notification removed event - com.geeksville.mesh#UserHandle{0},category=-1
11-11 21:56:01.102  6162  6997 I NotificationPipeline: Processing notification dismissal on phone: 0|com.geeksville.mesh|101|null|10476
11-11 21:56:01.102  6162  6997 I NotifDismissalHandler: Notification 0|com.geeksville.mesh|101|null|10476 dismissed on phone, deleting data item /bridger/stream_item:9ab4bedf:com.geeksville.mesh:101:null_tag:0~7Ccom.geeksville.mesh~7C101~7Cnull~7C10476
11-11 21:56:01.105  6162  6162 I NotifDismissalHandler: Received dismissal from watch, now dismissing on phone 0|com.geeksville.mesh|706835373|null|10476
11-11 21:56:01.275  2045  2045 I NotificationService: Cannot find enqueued record for key: 0|com.geeksville.mesh|101|null|10476
11-11 21:56:01.282  2045  2045 I NotificationService: Cannot find enqueued record for key: 0|com.geeksville.mesh|101|null|10476
11-11 21:56:01.287  6162  6997 I NotificationPipeline: Processing new notification: 0|com.geeksville.mesh|101|null|10476
11-11 21:56:01.287  6162  6997 I NotificationPipeline: parseAndSendNotification: 0|com.geeksville.mesh|101|null|10476, behavior=DEFAULT
11-11 21:56:01.290  6162  6997 I NotificationFilterModel: 0|com.geeksville.mesh|101|null|10476 filtered for reason: NON_CLEARABLE_NOTIFICATION
11-11 21:56:01.292 10260 10260 I NotificationListener: received notification posted event - com.geeksville.mesh#UserHandle{0},category=-1
11-11 21:56:48.161  2045  3570 I ActivityManager: Background started FGS: Allowed [callingPackage: com.geeksville.mesh; callingUid: 10476; uidState: TOP ; uidBFSL: [BFSL]; intent: Intent { xflg=0x4 cmp=com.geeksville.mesh/.service.MeshService }; code:PROC_STATE_TOP; tempAllowListReason:<null>; allowWiu:12; targetSdkVersion:36; callerTargetSdkVersion:36; startForegroundCount:10; bindFromPackage:null: isBindService:false]
11-11 21:56:48.407  6162  6997 I NotificationPipeline: Processing new notification: 0|com.geeksville.mesh|101|null|10476
11-11 21:56:48.407  6162  6997 I NotificationPipeline: parseAndSendNotification: 0|com.geeksville.mesh|101|null|10476, behavior=DEFAULT
11-11 21:56:48.409  6162  6997 I NotificationFilterModel: 0|com.geeksville.mesh|101|null|10476 filtered for reason: NON_CLEARABLE_NOTIFICATION
11-11 21:56:48.413 10260 10260 I NotificationListener: received notification posted event - com.geeksville.mesh#UserHandle{0},category=-1
11-11 21:56:48.418  6162  6997 I NotificationPipeline: Processing new notification: 0|com.geeksville.mesh|101|null|10476
11-11 21:56:48.419  6162  6997 I NotificationPipeline: parseAndSendNotification: 0|com.geeksville.mesh|101|null|10476, behavior=DEFAULT
11-11 21:56:48.419 10260 10260 I NotificationListener: received notification posted event - com.geeksville.mesh#UserHandle{0},category=-1
11-11 21:56:48.427  6162  6997 I NotificationFilterModel: 0|com.geeksville.mesh|101|null|10476 filtered for reason: NON_CLEARABLE_NOTIFICATION
11-11 21:56:48.440 10260 10260 I NotificationListener: received notification posted event - com.geeksville.mesh#UserHandle{0},category=-1
11-11 21:56:48.442  6162  6997 I NotificationPipeline: Processing new notification: 0|com.geeksville.mesh|101|null|10476
11-11 21:56:48.443  6162  6997 I NotificationPipeline: parseAndSendNotification: 0|com.geeksville.mesh|101|null|10476, behavior=DEFAULT
11-11 21:56:48.445  6162  6997 I NotificationFilterModel: 0|com.geeksville.mesh|101|null|10476 filtered for reason: NON_CLEARABLE_NOTIFICATION
11-11 21:56:50.306  6162  6997 I NotificationPipeline: Processing new notification: 0|com.geeksville.mesh|101|null|10476
11-11 21:56:50.308  6162  6997 I NotificationPipeline: parseAndSendNotification: 0|com.geeksville.mesh|101|null|10476, behavior=DEFAULT
11-11 21:56:50.314  6162  6997 I NotificationFilterModel: 0|com.geeksville.mesh|101|null|10476 filtered for reason: NON_CLEARABLE_NOTIFICATION
11-11 21:56:50.321 10260 10260 I NotificationListener: received notification posted event - com.geeksville.mesh#UserHandle{0},category=-1
```

### Additional information

Expected behavior in 2.7.5. This appears to be a regression in 2.7.6 open beta 4

### PR DESCRIPTION
**Pull request by mdecourcy**
This PR ensures the Android client always asks the radio for its buffered text messages after a disconnect/reconnect and captures the responses. We now persist the last StoreForward replay marker per device, issue a CLIENT_HISTORY request (and restart the RX collector) as soon as any transport returns to CONNECTED, and ship focused debug logs/tests. That brings Wi‑Fi/TCP reconnects back in line with BLE/2.7.5, so queued messages are delivered again.

To close #3672

big thanks to @dblaber / corruptedstack on discord for helping verify! My heltec just came in and I have also verified.

### CODE REVIEW

File: app/src/main/java/com/geeksville/mesh/service/MeshService.kt [hunk 1]
```diff
@@ -1393,22 +1581,22 @@ class MeshService : Service() {
                 }
 
                 PayloadVariantCase.FILEINFO -> { proto: MeshProtos.FromRadio -> handleFileInfo(proto.fileInfo) }
-
                 PayloadVariantCase.CLIENTNOTIFICATION -> { proto: MeshProtos.FromRadio ->
                     handleClientNotification(proto.clientNotification)
                 }
 
-                PayloadVariantCase.LOG_RECORD -> { proto: MeshProtos.FromRadio -> handleLogRecord(proto.logRecord) }
+                PayloadVariantCase.LOG_RECORD -> { proto: MeshProtos.FromRadio -> handleLogReord(proto.logRecord) }
```
Comment (jamesarich) [inline app/src/main/java/com/geeksville/mesh/service/MeshService.kt:1591]: oop looks like you undid my typo fix... and some of the logging I had added in #3691  for the bt connection, mind giving it another pass?

Comment (mdecourcy) [reply app/src/main/java/com/geeksville/mesh/service/MeshService.kt:1591]: My bad yeah i was in rebase hell for a bit there. On it

Comment (DaneEvans) [reply app/src/main/java/com/geeksville/mesh/service/MeshService.kt:1591]: When it gets too bad, cherrypicking the other way onto a new branch is often easier

File: app/src/main/java/com/geeksville/mesh/service/MeshService.kt [hunk 2]
```diff
@@ -1150,6 +1335,12 @@ class MeshService : Service() {
     // Update our model and resend as needed for a MeshPacket we just received from the radio
     private fun processReceivedMeshPacket(packet: MeshPacket) {
         val fromNum = packet.from
+
+        // FIXME, perhaps we could learn our node ID by looking at any to packets the radio
```
Comment (DaneEvans) [inline app/src/main/java/com/geeksville/mesh/service/MeshService.kt]: remaining fixme.

Comment (jamesarich) [reply app/src/main/java/com/geeksville/mesh/service/MeshService.kt]: i think this was pre-existing (and replaced)

File: app/src/main/java/com/geeksville/mesh/service/MeshService.kt [hunk 3]
```diff
@@ -1488,7 +1688,7 @@ class MeshService : Service() {
     }
 
     private fun handleChannel(ch: ChannelProtos.Channel) {
-        Timber.d("[channel] ${ch.toPIIString()}")
+        Timber.d("Received channel ${ch.index}")
```
Comment (jamesarich) [inline app/src/main/java/com/geeksville/mesh/service/MeshService.kt]: still looks like my logging format got overwritten `[proto]: message`

**Review by jamesarich — CHANGES_REQUESTED** [review]

**Review by jamesarich — APPROVED** [review]
