### PR TITLE
fix #3566: rangetest export not having distances

### LINKED ISSUE #3287: [Bug]: Distance in Meshtastic_rangetes.csv always zero
### Contact Details

_No response_

### Checklist

- [x] I am able to reproduce the bug with the latest version.

- [x] I made sure that there are no existing **OPEN or CLOSED issues** which I could contribute my information to.

- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

- [x] This issue contains only one bug.

- [x] I have read and understood the **Contribution Guidelines**.

- [x] I agree to follow this project's Code of Conduct

### Affected app version

2.7.11 29314197 google

### Affected Android version

Android 15

### Affected phone model

Samsung A26

### Affected node model

Lilygo T Lora

### Affected node firmware version

2.1-1.6

### Steps to reproduce the bug

App
Exporter les paquets test de portee

### Actual behavior

The distance is always zero or NULL.

Image

### Expected behavior

Image

### Screenshots/Screen recordings

_No response_

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DaneEvans**
Closes #3287 

The function to calculate distance from latlong pairs was just straight up wrong. returning numbers about E-7 out from the real distances. 
Also added unit to the export - hardcoded metric for now, but at least it shows the units.

### CODE REVIEW

File: feature/settings/src/main/kotlin/org/meshtastic/feature/settings/SettingsViewModel.kt [hunk 1]
```diff
@@ -142,16 +142,18 @@ constructor(
             // Capture the current node value while we're still on main thread
             val nodes = nodeRepository.nodeDBbyNum.value
 
+            // Converts a MeshProtos.Position (nullable) to a Position, but only if it's valid, otherwise returns null.
+            // The returned Position is guaranteed to be non-null and valid, or null if the input was null or invalid.
             val positionToPos: (MeshProtos.Position?) -> Position? = { meshPosition ->
-                meshPosition?.let { Position(it) }.takeIf { it?.isValid() == true }
+                meshPosition?.let { Position(it) }?.takeIf { it.isValid() }
```
Comment (NeimadTL) [inline feature/settings/src/main/kotlin/org/meshtastic/feature/settings/SettingsViewModel.kt:148]: Is there a difference ? or this is for shortness and conciseness ?

Comment (DaneEvans) [reply feature/settings/src/main/kotlin/org/meshtastic/feature/settings/SettingsViewModel.kt:148]: I let cursor do it ... 
Functionally they are the same. 

but isValid returns a bool anyway, by not making it tristate, we can drop the == true. 
And the change in the optional unwrapping allows for the case where 'it' is null.

Comment (NeimadTL) [reply feature/settings/src/main/kotlin/org/meshtastic/feature/settings/SettingsViewModel.kt:148]: Thanks for explanation. Didn't quite get your last sentence though,  what did you mean by "unwrapping"?

Comment (jamesarich) [reply feature/settings/src/main/kotlin/org/meshtastic/feature/settings/SettingsViewModel.kt:148]: > Thanks for explanation. Didn't quite get your last sentence though, what did you mean by "unwrapping"?

https://kotlinlang.org/docs/null-safety.html#safe-call-operator - just moved the `?` safety check out of the lambda, allowing it to only run when `Position(meshPosition)` is non-null
