### PR TITLE
Fix/2530 temp scaling

### LINKED ISSUE #2530: [Bug]: Set to Fahrenheit but still shows in Celsius scale but with a F°
### Contact Details

_No response_

### What happened?

Set to Fahrenheit but still shows in Celsius scale but with a F°

Image

### App Version

2.6.31

### Phone

Pixel 9 PRO XL, Android 16 Beta Q3

### Device

RAK19007, RAK4631

### Firmware

2.6.11

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by DaneEvans**
Closes #2530 

- Fahrenheit conversion was being done, but the soil temp copy overwrote the regular temp one. 

- Added testing

### CODE REVIEW

File: app/src/test/java/com/geeksville/mesh/ui/metrics/EnvironmentMetricsTest.kt [hunk 1]
```diff
@@ -0,0 +1,53 @@
+package com.geeksville.mesh.ui.metrics
```
Comment (DaneEvans) [inline app/src/test/java/com/geeksville/mesh/ui/metrics/EnvironmentMetricsTest.kt:18]:
```suggestion
/*
 * Copyright (c) 2025 Meshtastic LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.geeksville.mesh.ui.metrics
```
