### PR TITLE
Fix #3468 - Timed Mute

### LINKED ISSUE #3468: [Bug]: 2.7.3 timed channel mute no longer working
### Contact Details

bitflip

### Checklist

- [x] I am able to reproduce the bug with the latest version.

- [x] I made sure that there are no existing **OPEN or CLOSED issues** which I could contribute my information to.

- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

- [x] This issue contains only one bug.

- [x] I have read and understood the **Contribution Guidelines**.

- [x] I agree to follow this project's Code of Conduct

### Affected app version

2.7.3 fdroid

### Affected Android version

16, 13

### Affected phone model

Pixel 6, Galaxy A01

### Affected node model

Heltec v3, seeeeeeed nrf+wio

### Affected node firmware version

2.7.9

### Steps to reproduce the bug

1. Go to "Conversations" tab
2. Long press a channel
3. Tap the speaker icon
4. Choose either "8 hours" or "1 week" and press OK

### Actual behavior

The channel remains un-muted. "Always" and "Unmute" options work as usual.
Tested on 2 different android devices and nodes.

### Expected behavior

The app should mute notifications from the chosen channel for the selected period of time.

### Screenshots/Screen recordings

_No response_

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DaneEvans**
Fix timed mute. closes #3468 
- add text above with current status.
    - lists multiple if multiple are selected.

image

### CODE REVIEW

File: core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt [hunk 1]
```diff
@@ -62,5 +64,26 @@ private fun formatUptime(seconds: Long): String {
...
+}
+
+/**
+ * Formats remaining mute time in a human-readable format
+ *
+ * @param remainingMillis The remaining time in milliseconds
+ * @return Formatted string as "2d, 3.5h" or "Not muted" if time has expired
+ */
+fun formatMuteRemainingTime(remainingMillis: Long): String {
+    if (remainingMillis <= 0) return "Not muted"
```
Comment (poliver) [inline core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt]: Use the string resource

File: core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt [hunk 2]
```diff
@@ -62,5 +64,26 @@ private fun formatUptime(seconds: Long): String {
         .joinToString(" ")
 }
 
-@Suppress("MagicNumber")
-fun onlineTimeThreshold() = (System.currentTimeMillis() / 1000 - 2 * 60 * 60).toInt()
+fun onlineTimeThreshold(): Int {
+    val currentSeconds = System.currentTimeMillis() / TimeUnit.SECONDS.toMillis(1)
+    return (currentSeconds - ONLINE_WINDOW_HOURS * TimeUnit.HOURS.toSeconds(ONLINE_WINDOW_HOURS.toLong())).toInt()
```
Comment (poliver) [inline core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt]: Should this be just `(currentSeconds - TimeUnit.HOURS.toSeconds(ONLINE_WINDOW_HOURS.toLong()))`?

File: core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt [hunk 3]
```diff
@@ -62,5 +64,26 @@ private fun formatUptime(seconds: Long): String {
         .joinToString(" ")
 }
 
-@Suppress("MagicNumber")
-fun onlineTimeThreshold() = (System.currentTimeMillis() / 1000 - 2 * 60 * 60).toInt()
+fun onlineTimeThreshold(): Int {
```
Comment (poliver) [inline core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt:67]: Mind documenting this? I'm not exactly sure what it's for.

File: app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt [hunk 4]
```diff
@@ -238,6 +247,32 @@ fun MuteNotificationsDialog(
...
+                    // Show current mute status
+                    selectedContactKeys.forEach { contactKey ->
+                        contactSettings[contactKey]?.let { settings ->
+                            val now = System.currentTimeMillis()
+                            val statusText =
+                                when {
+                                    settings.muteUntil > 0 && settings.muteUntil != Long.MAX_VALUE -> {
+                                        val remaining = settings.muteUntil - now
+                                        if (remaining > 0) {
+                                            stringResource(R.string.mute_status_muted_for) +
```
Comment (poliver) [inline app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt]: Might want to change this and below to formatted strings, since translations can get wonky with concatenation.

File: core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt (hunk 2 above)
Comment (poliver) [reply core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt]: Also, `java.time`/`kotlinx.datetime` make these calculations easier with `Instant` and `Duration` which have some arithmetic operators.

File: core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt (hunk 3 above)
Comment (DaneEvans) [reply core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt:67]: NFI  - I just removed the magic numbers and made it readable.

File: core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt (hunk 1 above)
Comment (DaneEvans) [reply core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt]: It should never get that - it get's intercepted at the level above, and this file doesn't have access to strings from memory. 

i could assert, but that seems less pleasent.

File: app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt (hunk 4 above)
Comment (DaneEvans) [reply app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt]: Yeah, I didn't like it. In hindsight it's probably better to do 2 strings: 

```
if days
    stringA, A, B
else 
    stringB, B 
```

File: core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt (hunk 2 above)
Comment (DaneEvans) [reply core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt]: Certainly looks like it should be.

File: core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt (hunk 1 above)
Comment (DaneEvans) [reply core/model/src/main/kotlin/org/meshtastic/core/model/util/DateTimeUtils.kt]: the only 'strings' returned by the function in normal operation is "00d 0.0h" which matches our hardcoding in other places.

File: app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt (hunk 4 above)
Comment (poliver) [reply app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt]: Just realized these are plurals, too - can of worms. Looks good as-is with your changes 😅

Comment (DaneEvans) [reply app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt]: yeah, in is better than perfect in this case.
